### ISSUE TITLE
Trouble getting script to function, need API key??

### ISSUE THREAD

**Issue by johnkcox** [astroscrum/hubot-astroscrum#7]
Installed hubot-astroscrum per instructions, running on heroku, using slack. Only thing that appears to be amiss is that I don't have an API key (the link on your http://docs.astroscrum.com/ page to get a free API key just redirects to the home page in Chrome). 

Here's what the logs say in heroku:

```
2015-12-04T15:44:04.694458+00:00 app[web.1]: [Fri Dec 04 2015 15:44:04 GMT+0000 (UTC)] ERROR TypeError: Cannot read property '_private' of null
2015-12-04T15:44:04.694462+00:00 app[web.1]:   at /app/node_modules/hubot-astroscrum/src/astroscrum.coffee:53:43, <js>:31:32
2015-12-04T15:44:04.694464+00:00 app[web.1]:   at try_callback (/app/node_modules/hubot-astroscrum/node_modules/redis/index.js:592:9)
2015-12-04T15:44:04.694465+00:00 app[web.1]:   at RedisClient.return_reply (/app/node_modules/hubot-astroscrum/node_modules/redis/index.js:685:13)
2015-12-04T15:44:04.694467+00:00 app[web.1]:   at ReplyParser.emit (events.js:95:17)
2015-12-04T15:44:04.694466+00:00 app[web.1]:   at ReplyParser.<anonymous> (/app/node_modules/hubot-astroscrum/node_modules/redis/index.js:321:14)
2015-12-04T15:44:04.694469+00:00 app[web.1]:   at ReplyParser.execute (/app/node_modules/hubot-astroscrum/node_modules/redis/lib/parser/javascript.js:203:22)
2015-12-04T15:44:04.694468+00:00 app[web.1]:   at ReplyParser.send_reply (/app/node_modules/hubot-astroscrum/node_modules/redis/lib/parser/javascript.js:300:10)
2015-12-04T15:44:04.694476+00:00 app[web.1]:   at RedisClient.on_data (/app/node_modules/hubot-astroscrum/node_modules/redis/index.js:547:27)
2015-12-04T15:44:04.694479+00:00 app[web.1]:   at Socket.<anonymous> (_stream_readable.js:765:14)
2015-12-04T15:44:04.694478+00:00 app[web.1]:   at Socket.emit (events.js:95:17)
2015-12-04T15:44:04.694477+00:00 app[web.1]:   at Socket.<anonymous> (/app/node_modules/hubot-astroscrum/node_modules/redis/index.js:102:14)
2015-12-04T15:44:04.694480+00:00 app[web.1]:   at emitReadable_ (_stream_readable.js:427:10)
2015-12-04T15:44:04.694479+00:00 app[web.1]:   at Socket.emit (events.js:92:17)
2015-12-04T15:44:04.694481+00:00 app[web.1]:   at emitReadable (_stream_readable.js:423:5)
2015-12-04T15:44:04.694483+00:00 app[web.1]:   at TCP.onread (net.js:529:21)
2015-12-04T15:44:04.694481+00:00 app[web.1]:   at readableAddChunk (_stream_readable.js:166:9)
2015-12-04T15:44:04.694482+00:00 app[web.1]:   at Socket.Readable.push (_stream_readable.js:128:10)
```

**Comment by trivago-hdilaver** [comment]
+1 here 

```
2016-01-27T18:34:08.621467+00:00 heroku[web.1]: State changed from starting to up
2016-01-27T18:34:10.590631+00:00 app[web.1]: [Wed Jan 27 2016 18:34:10 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'auth_token' of undefined
2016-01-27T18:34:10.590637+00:00 app[web.1]:   at /app/node_modules/hubot-astroscrum/src/astroscrum.coffee:188:9, <js>:169:72
2016-01-27T18:34:10.590638+00:00 app[web.1]:   at /app/node_modules/hubot-astroscrum/src/astroscrum.coffee:93:5, <js>:110:7
2016-01-27T18:34:10.590639+00:00 app[web.1]:   at Request._callback (/app/node_modules/hubot-astroscrum/src/astroscrum.coffee:63:7, <js>:56:16)
2016-01-27T18:34:10.590640+00:00 app[web.1]:   at Request.self.callback (/app/node_modules/hubot-astroscrum/node_modules/request/request.js:198:22)
2016-01-27T18:34:10.590642+00:00 app[web.1]:   at Request.<anonymous> (/app/node_modules/hubot-astroscrum/node_modules/request/request.js:1035:10)
2016-01-27T18:34:10.590642+00:00 app[web.1]:   at Request.emit (events.js:117:20)
2016-01-27T18:34:10.590643+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot-astroscrum/node_modules/request/request.js:962:12)
2016-01-27T18:34:10.590641+00:00 app[web.1]:   at Request.emit (events.js:98:17)
2016-01-27T18:34:10.590644+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2016-01-27T18:34:10.590645+00:00 app[web.1]:   at _stream_readable.js:944:16
2016-01-27T18:34:10.590646+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
2016-01-27T18:34:10.590647+00:00 app[web.1]:
2016-01-27T18:34:10.611494+00:00 app[web.1]: [Wed Jan 27 2016 18:34:10 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'auth_token' of undefined
2016-01-27T18:34:10.611499+00:00 app[web.1]:   at /app/scripts/astroscrum.coffee:190:9, <js>:169:72
2016-01-27T18:34:10.611502+00:00 app[web.1]:   at /app/scripts/astroscrum.coffee:93:5, <js>:110:7
2016-01-27T18:34:10.611506+00:00 app[web.1]:   at Request.<anonymous> (/app/node_modules/request/request.js:1036:10)
2016-01-27T18:34:10.611503+00:00 app[web.1]:   at Request._callback (/app/scripts/astroscrum.coffee:63:7, <js>:56:16)
2016-01-27T18:34:10.611504+00:00 app[web.1]:   at Request.self.callback (/app/node_modules/request/request.js:199:22)
2016-01-27T18:34:10.611505+00:00 app[web.1]:   at Request.emit (events.js:98:17)
2016-01-27T18:34:10.611507+00:00 app[web.1]:   at Request.emit (events.js:117:20)
2016-01-27T18:34:10.611507+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:963:12)
2016-01-27T18:34:10.611508+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2016-01-27T18:34:10.611509+00:00 app[web.1]:   at _stream_readable.js:944:16
2016-01-27T18:34:10.611510+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
2016-01-27T18:34:10.611511+00:00 app[web.1]:
2016-01-27T18:34:10.693022+00:00 heroku[web.1]: Process exited with status 0
```

**Comment by NeilHanlon** [comment]
+1 here too...

@mmcdaris @jpsilvashy  ?

**Comment by jpsilvashy** [comment]
@NeilHanlon @trivago-hdilaver @johnkcox sorry about the delay on this, @mmcdaris and I have been working on an entirely new version of the API and have turned off the API server since we've had a lot of companies and people sign up, and we weren't able to provide them with active support.

Our plan is to get the new API done shortly, sorry about all this, you're better off removing the script from your hubot for the time being.

**Comment by NeilHanlon** [comment]
@jpsilvashy Any update on the API? Really looking forward to implementing this into our agile workflow.

**Comment by VigneshPT** [comment]
@jpsilvashy I still see this issue. Why is this closed? How do I get an API Key?
